---
- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Add PostgreSQL repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    filename: postgresql
    state: present
  become: yes

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present
    update_cache: yes
  become: yes

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
    enabled: yes
  become: yes
