---
- name: Install packages
  pacman:
    name: "{{ item }}"
  with_items:
    - postgresql
    - python-psycopg2
  become: yes

- name: Initialize database
  command: initdb --locale en_US.UTF-8 -D "/var/lib/postgres/data"
  args:
    creates: /var/lib/postgres/data/postgresql.conf
  become: yes
  become_user: postgres

- name: Start service
  systemd:
    name: postgresql
    state: started
    enabled: yes
  become: yes

- name: Create user
  postgresql_user:
    name: sestrella
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: Create database
  postgresql_db:
    name: sestrella
    owner: sestrella
  become: yes
  become_user: postgres
