---
- name: Add repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    filename: postgresql
    state: present

- name: Install package
  apt:
    name: postgresql
    update_cache: yes
    state: present

- name: Enable service
  service:
    name: postgresql
    enabled: yes
    state: started
