---
- name: Add repository key
  apt_key:
    url: "{{ postgresql_apt_key_url }}"
    state: present

- name: Add repository
  apt_repository:
    repo: "{{ postgresql_apt_repository_repo }}"
    filename: postgresql
    state: present

- name: Install package
  apt:
    name: postgresql
    update_cache: yes
    state: present

- name: Enable service
  service:
    name: postgresql
    enabled: yes
    state: started

- name: Add database user
  postgresql_user:
    name: "{{ ansible_user_id }}"
    state: present

- name: Create database
  postgresql_db:
    name: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
