---
- name: Add postgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    filename: postgresql
    state: present

- name: Install postgresql
  apt:
    name: postgresql
    update_cache: yes
    state: present

- name: Start postgresql service
  service:
    name: postgresql
    state: started
    enabled: yes
