---
- name: Add key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main"
    filename: "postgresql"
    state: present
  become: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - libpq-dev
    - postgresql
    - python-psycopg2
  become: yes

- name: Add role
  postgresql_user:
    name: "{{ ansible_user_id }}"
    role_attr_flags: SUPERUSER
  become: yes
  become_user: postgres

- name: Add database
  postgresql_db:
    name: "{{ ansible_user_id }}"
    owner: "{{ ansible_user_id }}"
  become: yes
  become_user: postgres
