---
- name: Install zsh
  apt:
    name: zsh
    state: present
  become: true

- name: Clone prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto
    recursive: yes

- name: Symlink prezto files
  file:
    src: ~/.zprezto/runcoms/{{ item }}
    dest: ~/.{{ item }}
    state: link
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv

- name: Set default shell
  user:
    name: sestrella
    shell: /bin/zsh
  become: true
