---
- name: Install package
  pacman:
    name: "{{ item }}"
  with_items:
    - mongodb
    - mongodb-tools
  become: yes

- name: Start service
  systemd:
    name: mongodb
    state: started
    enabled: yes
  become: yes
