---
- name: Add repository key
  apt_key:
    id: 0C49F3730359A14518585931BC711F9BA15703C6
    keyserver: hkp://keyserver.ubuntu.com:80

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64,arm64] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    filename: mongodb

- name: Install package
  apt:
    name: mongodb-org
    update_cache: yes
