---
- name: Install neovim dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  become: yes

- name: Add neovim repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
  become: yes

- name: Install neovim
  apt:
    name: neovim
    state: present
  become: yes
