---
- name: Add key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google
    state: present
  become: yes

- name: Install package
  apt:
    name: google-chrome-stable
    state: present
    update_cache: yes
  become: yes
