---
- name: Install package
  apt:
    name: zsh
    state: present
  become: yes

- name: Symlink configuration file
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: ~/.zshrc
    state: link

- name: Create directory
  file:
    path: ~/.zsh
    state: directory

- name: Change shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes

- name: Clone framework
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto

- name: Symlink configuration files
  file:
    src: "~/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv

- name: Symlink configuration file
  file:
    src: "{{ role_path }}/files/zpreztorc"
    dest: ~/.zpreztorc
    state: link
