---
- name: Install zsh packages
  apt:
    name: zsh
    state: present
  become: true

- name: Clone prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto

- name: Symlink prezto files
  file:
    src: ~/.zprezto/runcoms/{{ item }}
    dest: ~/.{{ item }}
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc

- name: Symlink zshrc
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: ~/.zshrc
    state: link
