---
- name: Install package
  apt:
    name: zsh
    state: present
  become: yes

- name: Change shell
  user:
    name: sestrella
    shell: /bin/zsh
  become: yes

- name: Clone framework
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto

- name: Symlink configuration files
  file:
    src: "~/.zprezto/runcoms/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zshrc
