---
- name: Add repository key
  apt_key:
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  become: yes

- name: Add repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    filename: spotify
    state: present
  become: yes

- name: Install package
  apt:
    name: spotify-client
    update_cache: yes
    state: present
  become: yes

