---
- name: Add repository
  apt_repository:
    repo: ppa:atareao/atareao
    filename: atareao
    state: present
  become: yes

- name: Install package
  apt:
    name: touchpad-indicator
    update_cache: yes
    state: present
  become: yes
