---
- name: Install package
  apt:
    name: git
    state: present
  become: yes

- name: Symlink configuration file
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: ~/.gitconfig
    state: link
