---
- name: Install package
  pacman:
    name: git
    state: present
  become: yes

- name: Symlink configuration
  file:
    src: "{{ role_path }}/files/gitconfig"
    dest: ~/.gitconfig
    state: link
