set nocompatible
filetype off 

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-sensible'

call vundle#end()
filetype plugin indent on

set noswapfile
set number

set expandtab
set tabstop=2
set shiftwidth=2

set hlsearch

syntax enable
set background=dark
colorscheme solarized

let mapleader = ","

map <leader>n :NERDTreeToggle<CR>

let g:airline_powerline_fonts = 1
