call plug#begin('~/.vim/plugged')

Plug 'Quramy/tsuquyomi'
Plug 'Shougo/vimproc.vim', { 'do' : 'make' }
Plug 'altercation/vim-colors-solarized'
Plug 'bling/vim-airline'
Plug 'kien/ctrlp.vim'
Plug 'leafgarland/typescript-vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-sensible'
Plug 'vim-syntastic/syntastic'

call plug#end()

syntax enable
set background=dark
colorscheme solarized

set backupdir=~/.vim/backup//
set directory=~/.vim/swap//
set undodir=~/.vim/undo//

set number

set expandtab
set shiftwidth=2
set smarttab
set tabstop=2

let mapleader = ','

let g:airline_powerline_fonts = 1
let g:ctrlp_map = '<Leader>p'
let g:syntastic_typescript_checkers = ['tsuquyomi']
let g:tsuquyomi_disable_quickfix = 1

if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
  let g:ctrlp_use_caching = 0
endif

map <Leader>n :NERDTreeToggle<CR>
