---
- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.10.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose

- name: Change docker-compose permissions
  file:
    path: /usr/local/bin/docker-compose
    group: docker
    mode: g+x
