---
- name: Install tmux
  apt:
    name: tmux
    state: present
  become: yes

- name: Install tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

- name: Copy tmux.conf file
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: ~/.tmux.conf
    state: link
