---
- name: Install host modules
  pacman:
    name: virtualbox-host-modules-arch
    state: present
  become: yes

- name: Install package
  pacman:
    name: virtualbox
    state: present
  become: yes
