---
- name: Install package
  apt:
    name: tmux
    state: present
  become: yes

- name: Install plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm