---
- name: Add mongodb key
  apt_key:
    id: EA312927
    keyserver: hkp://keyserver.ubuntu.com:80
  become: yes

- name: Add mongodb repository
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse'
  become: yes

- name: Install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
  become: yes
