---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ pyenv.dependencies }}"
  become: yes

- name: Clone pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ pyenv.root }}"
