---
- name: Install package
  pacman:
    name: docker
    state: present
  become: yes

- name: Start service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add group to user
  user:
    name: sestrella
    groups: docker
    append: yes
  become: yes
