---
- name: Add repository key
  apt_key:
    url: https://apt.dockerproject.org/gpg

- name: Add repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo/ ubuntu-{{ ansible_distribution_release }} main"
    filename: docker

- name: Install package
  apt:
    name: docker-engine
    update_cache: yes

- name: Add user to group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Download compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.11.1/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0750
