---
- name: Install package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - fonts-powerline
    - silversearcher-ag
    - vim
  become: yes

- name: Create directories
  file:
    path: "~/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - backup
    - swap
    - undo

- name: Install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
