---
- name: Install package
  pacman:
    name: vim
  become: yes

- name: Create directories
  file:
    path: "~/.vim/{{ item }}"
    state: directory
  with_items:
    - autoload
    - backup
    - swap
    - undo

- name: Install plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Symlink configuration file
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: ~/.vimrc
    state: link

- name: Install plugins
  shell: vim +PlugInstall +qall
