---
- name: Install package
  git:
    repo: https://github.com/Eriner/zim.git
    dest: "{{ ansible_user_dir }}/.zim"
    recursive: yes

- name: Symlink files
  file:
    src: "{{ ansible_user_dir }}/.zim/templates/{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    state: link
  with_items:
    - zimrc
    - zlogin
    - zshrc
