---
- name: Clone zim
  git:
    repo: https://github.com/Eriner/zim.git
    dest: ~/.zim
    recursive: yes

- name: Symlink file
  file:
    src: ~/.zim/templates/zlogin
    dest: ~/.zlogin
    state: link
