---
- name: Add repository key
  apt_key:
    id: 575159689BEFB442
    keyserver: hkp://keyserver.ubuntu.com:80
  become: yes

- name: Add repository
  apt_repository:
    repo: deb http://download.fpcomplete.com/ubuntu xenial main
    state: present
  become: yes

- name: Install stack
  apt:
    name: stack
    state: present
  become: yes

- name: Create ~/.stack directory
  file:
    path: ~/.stack
    state: directory

- name: Copy stack-config.yaml file
  file:
    src: "{{ role_path }}/files/stack-config.yaml"
    dest: ~/.stack/config.yaml
    state: link
