---
- name: Add repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    filename: neovim
    state: present
  become: yes

- name: Install package
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: yes
