---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
  become: yes

- name: Add repository
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    filename: neovim
    state: present
  become: yes

- name: Install package
  apt:
    name: neovim
    state: present
    update_cache: yes
  become: yes
